###############
# test workflow for Plater
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.0]
    services:
      neo4j:
        image: neo4j:5.10.0
        env:
          NEO4J_AUTH: neo4j/plater_testing_pw
          NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
          - '7474:7474'
          - '7687:7687'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create environment variables
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f PLATER/requirements.txt ]; then pip install -r PLATER/requirements.txt; fi

      - name: Set up Neo4j data
        run: |
          python PLATER/tests/initialize_db.py "${GITHUB_SHA}"

      - name: Run the tests
        run: |
          pytest PLATER/tests/
