###############
# test workflow for Plater
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.0]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create environment variables
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f PLATER/requirements.txt ]; then pip install -r PLATER/requirements.txt; fi
      - name: Run the tests
        run: |
          python -m pytest PLATER/tests/
